export const robots =[
    {
        id:1,
        name:'ryan',
        email:'ryns118＠gmail.com'
    },
    {
        id:2,
        name:'purple',
        email:'purple＠gmail.com'
    },
    {
        id:3,
        name:'boris',
        email:'boris＠gmail.com'
    },
    {
        id:4,
        name:'john',
        email:'john＠gmail.com'
    },
    {
        id:5,
        name:'may',
        email:'may＠gmail.com'
    },
    {
        id:6,
        name:'amie',
        email:'amie＠gmail.com'
    },
    {
        id:7,
        name:'ken',
        email:'ken＠gmail.com'
    },
    {
        id:8,
        name:'josh',
        email:'josh＠gmail.com'
    },
    {
        id:9,
        name:'lotus',
        email:'lotus＠gmail.com'
    },
    {
        id:10,
        name:'ben',
        email:'ben＠gmail.com'
    },
]